### ISSUE TITLE
How do I get involved?

### ISSUE THREAD

**Issue by navdeep-G** [kasaai/explain-ml-pricing#1]

**Comment by kevinykuo** [comment]
You've dropped by at the perfect time! @daniellupton and I are about to start making progress on this. We can definitely use some help with model explanation/interpretation techniques once we have some models built (we'll be piggybacking off of https://github.com/kasaai/pc-pricing-tutorial). Stop by #explain-ml-pricing on the Kasa AI slack and we can chat.

**Comment by navdeep-G** [comment]
Great, what is the slack handle for Kasa AI?
