### ISSUE TITLE
Reconcile rate relativities vs. ML

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/explain-ml-pricing#16]
From the ratemaking section
```
3. Perform analysis on the data, employing desired method or methods to estimate
needed rate relativites
4. Select final rate relativities based on rate indications
5. Present rates to the reglator, including explanation of the steps followed to derive
the rates
6. Answer questions from regulators regarding the method employed
The focus of this paper is on steps 5 and 6
```
I don't think we can get at relativities with ML models, so maybe we need to revise this bit to say 4-5 will be different in the world with ML models. It may also make sense to point out somewhere that we'll be using ML as a drop-in replacement for GLM rather than for feature engineering only.

**Comment by daniellupton** [comment]
I think we can generalize that a bit, yeah. I will propose some rewording in my next pull, but feel free to add more if you want to elaborate.
