### ISSUE TITLE
ML models and "deterministic"

### ISSUE THREAD

**Issue by kevinykuo** [kasaai/explain-ml-pricing#18]
> Because many machine learning models are deterministic, they may not admit of standard metrics for model comparison (e.g., it’s not straightforward to calculate an AIC over a neural network).

We'll want to reword this e.g. "does not assume an underlying stochastic process" since deterministic has a different meaning in ML

**Comment by daniellupton** [comment]
Added some proposed wording in latest pull request (forthcoming).
