### ISSUE TITLE
Standardized Set of Questions

### ISSUE THREAD

**Issue by daniellupton** [kasaai/explain-ml-pricing#28]
This is an open-ended question that I mentioned on our call. Is it realistic to assume that there could be a single standardized set of questions that, properly answered, could reasonably qualify any model?

For example, suppose the question were simply:
"Demonstrate that the rates produced by the model are not inadequate, excessive, or unfairly discriminatory."

That would _technically_ address any concern insofar as a successful answer would mean the model could be approved, but realistically speaking, chances are that it would not produce good regulatory outcomes since modelers wouldn't really know how to answer that.

What I mean to say is that I guess after reading the paper over, I prefer to think of the "question and answer" framework in terms of a set of idealized questions and that a perfect set of questions may not exist that cover every model. My sense has been that no matter how detailed your questions and how varied, you'll probably see some model that leaves you with additional questions from time to time.

That is, I see the question-and-answer thing more as a metaphor for how the actuary should conceptualize the requirement to communicate to intended users of a model than as a suggestion to actually come up with a list of specific questions.

IF you agree - and I suppose that could be a big if - then we may want to consider rewording some of the language around the "standardized set of questions" a bit accordingly.

**Comment by kevinykuo** [comment]
Agreed! I think a standard set of questions will come with too many caveats and/or be gameable. I think we can relax that a bit, so please go ahead and suggest the rewording in #27 especially around https://github.com/kasaai/explain-ml-pricing/blob/472e1b46f450c8ac3ca104725c823c5908532b2a/manuscript/manuscript.Rmd#L365
