### ISSUE TITLE
Error in R code of "explain.R" 

### ISSUE THREAD

**Issue by wxhmath** [kasaai/explain-ml-pricing#36]
When run the R codes:
fi <- ingredients::feature_importance(
explainer_nn,
loss_function = function(observed, predicted, weights) {
sqrt(
      sum(((observed - predicted) ^ 2 * weights) /sum(weights))
    )
  },
  weights = testing_data$exposure,
  variables = predictors,
)
the result is **“Error in loss_function(observed, predict_function(x, sampled_data)) : argument "weights" is missing, with no default”.**
The problem should be “loss_function”,but I don’t know why.

**Comment by kevinykuo** [comment]
I think I forgot to send a PR upstream to enable weights in the loss function. Will address this before publication, either pointing to a fork or getting the change merged in DALEX.

**Comment by wxhmath** [comment]
Dear Professor Kevin Kuo:
Thanks for your reply! And I find  that in my loss data, the time exposure v ∈ (0, 1] should not be considered in a linear fashion λ(x)v, but the general approach with regression function µ as µ(x, v)  is more appropriate. The result is consistent with Andrea Ferrario et al.(2018).Best wishes! 



--


王选鹤  副教授
东北财经大学金融学院
保险与精算系 系主任
辽宁省大连市沙河口区尖山街217号


Wang Xuanhe
Associate Professor
School of Finance
Dongbei University of Finance and Economics



At 2020-02-26 05:34:54, "Kevin Kuo" <notifications@github.com> wrote:

I think I forgot to send a PR upstream to enable weights in the loss function. Will address this before publication, either pointing to a fork or getting the change merged in DALEX.
